name = "guess-who"
main = "src/index.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./src/static"

[[kv_namespaces]]
binding = "GAME_SESSIONS"
id = "placeholder-session-kv"
preview_id = "placeholder-session-pv"

[[kv_namespaces]]
binding = "CHARACTER_CACHE"
id = "placeholder-character-kv"
preview_id = "placeholder-character-pv"

[env.production]
name = "guess-who"

[env.preview]
name = "guess-who-preview"
