export default [
  { name: 'Albert', hairColor: 'brown', eyeColor: 'black', gender: 'male', glasses: false, hat: false, hairLength: 'short', facialHair: false, skinTone: 'dark' },
  { name: 'Bobby', hairColor: 'blonde', eyeColor: 'green', gender: 'male', glasses: true, hat: false, hairLength: 'medium', facialHair: false, skinTone: 'light' },
  { name: 'Brooke', hairColor: 'red', eyeColor: 'blue', gender: 'male', glasses: false, hat: false, hairLength: 'long', facialHair: false, skinTone: 'light' },
  { name: 'Clyde', hairColor: 'black', eyeColor: 'brown', gender: 'male', glasses: false, hat: false, hairLength: 'short', facialHair: true, skinTone: 'dark' },
  { name: 'Elliott', hairColor: 'bald', eyeColor: 'green', gender: 'male', glasses: true, hat: false, hairLength: 'bald', facialHair: false, skinTone: 'light' },
  { name: 'Garrett', hairColor: 'red', eyeColor: 'blue', gender: 'male', glasses: false, hat: false, hairLength: 'long', facialHair: false, skinTone: 'light' },
  { name: 'Henry', hairColor: 'blonde', eyeColor: 'blue', gender: 'male', glasses: false, hat: false, hairLength: 'short', facialHair: false, skinTone: 'light' },
  { name: 'Jesse', hairColor: 'black', eyeColor: 'brown', gender: 'male', glasses: false, hat: false, hairLength: 'short', facialHair: false, skinTone: 'dark' },
  { name: 'Ada', hairColor: 'red', eyeColor: 'blue', gender: 'female', glasses: false, hat: false, hairLength: 'long', facialHair: false, skinTone: 'light' },
  { name: 'Alice', hairColor: 'black', eyeColor: 'blue', gender: 'female', glasses: false, hat: false, hairLength: 'long', facialHair: false, skinTone: 'light' },
  { name: 'Brigitte', hairColor: 'blonde', eyeColor: 'blue', gender: 'female', glasses: false, hat: false, hairLength: 'long', facialHair: false, skinTone: 'light' },
  { name: 'Cheryl', hairColor: 'red', eyeColor: 'blue', gender: 'female', glasses: false, hat: false, hairLength: 'short', facialHair: false, skinTone: 'light' },
  { name: 'Daphne', hairColor: 'blonde', eyeColor: 'blue', gender: 'female', glasses: false, hat: false, hairLength: 'long', facialHair: false, skinTone: 'light' },
  { name: 'Ellen', hairColor: 'black', eyeColor: 'blue', gender: 'female', glasses: false, hat: false, hairLength: 'long', facialHair: false, skinTone: 'light' },
  { name: 'Fran', hairColor: 'bald', eyeColor: 'blue', gender: 'female', glasses: false, hat: false, hairLength: 'bald', facialHair: false, skinTone: 'light' },
  { name: 'Greta', hairColor: 'blonde', eyeColor: 'blue', gender: 'female', glasses: true, hat: false, hairLength: 'medium', facialHair: false, skinTone: 'light' },
  { name: 'Ian', hairColor: 'bald', eyeColor: 'blue', gender: 'male', glasses: false, hat: false, hairLength: 'bald', facialHair: false, skinTone: 'light' },
  { name: 'Jack', hairColor: 'black', eyeColor: 'blue', gender: 'male', glasses: true, hat: false, hairLength: 'short', facialHair: false, skinTone: 'light' },
  { name: 'Larry', hairColor: 'blonde', eyeColor: 'blue', gender: 'male', glasses: false, hat: false, hairLength: 'long', facialHair: false, skinTone: 'light' },
  { name: 'Mort', hairColor: 'bald', eyeColor: 'blue', gender: 'male', glasses: false, hat: false, hairLength: 'bald', facialHair: false, skinTone: 'light' },
  { name: 'Peter', hairColor: 'red', eyeColor: 'blue', gender: 'male', glasses: false, hat: false, hairLength: 'long', facialHair: false, skinTone: 'light' },
  { name: 'Sam', hairColor: 'black', eyeColor: 'blue', gender: 'male', glasses: false, hat: false, hairLength: 'short', facialHair: false, skinTone: 'light' },
  { name: 'Victor', hairColor: 'black', eyeColor: 'blue', gender: 'male', glasses: true, hat: false, hairLength: 'short', facialHair: false, skinTone: 'light' },
  { name: 'Wendy', hairColor: 'blonde', eyeColor: 'blue', gender: 'female', glasses: false, hat: false, hairLength: 'long', facialHair: false, skinTone: 'light' },
];
